# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117edfa86d429f70e2cd6876bb9442953c2af09dee93314a6346e68d4c1064b4a476673396154bc924bb2232da15ad51e882a9464d266b983e11665389535f47

test:
  secret_key_base: 364691fde7d95e1ba8e17d00e23a5263af74328e78a9efaffedf586657a711506642d110de98ea46ff55911ad6a0cf19bf856701d122bea8c356c47f496c62e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
